### ISSUE TITLE
Steeltoe.CircuitBreaker.Hystrix.MetricsStream.RabbitMetricsStreamPublisher:Error: Error creating connection/channel, metrics streaming disabled

### ISSUE THREAD

**Issue by ravichigurupalli** [SteeltoeOSS/Samples#159]
Hi All,

I am facing below issue when i am debugging in local .net core 2.1 application and it is going to fallback method. Few days back these hytrx commands are working perfectly don't have any changes in configuration side.
And i am using Steeltoe.CircuitBreaker.Hystrix.MetricsStreamCore and Steeltoe.CircuitBreaker.HystrixCore are 2.1.1 version. Please help me.

Steeltoe.CircuitBreaker.Hystrix.MetricsStream.RabbitMetricsStreamPublisher:Error: Error creating connection/channel, metrics streaming disabled: RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=530, text="NOT_ALLOWED - vhost / not found", classId=10, methodId=40, cause=
at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
at RabbitMQ.Client.Impl.ModelBase.ConnectionOpen(String virtualHost, String capabilities, Boolean insist)
at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
--- End of inner exception stack trace ---
at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
at Steeltoe.CircuitBreaker.Hystrix.MetricsStream.RabbitMetricsStreamPublisher.EnsureConnection()
The thread 0x2c94 has exited with code 0 (0x0).
Exception thrown: 'System.NullReferenceException' in Dell.Product.TransformLayer.Services.dll
Steeltoe.CircuitBreaker.Hystrix.MetricsStream.RabbitMetricsStreamPublisher:Debug: Discarding Hystrix Metrics, no connection

**Comment by TimHess** [comment]
1. Steeltoe 2.1.1 was released almost 2 years ago, please try updating to newer packages
1. This looks like a connection issue with RabbitMQ - is your local service running and have you configured the application to know how to find it?

**Comment by ravichigurupalli** [comment]
Thanks a lot for your quick response Hess.
1. I am implementing CircuitBreaker in an existing application, in that application, some of the steelteo packages are 2.1.1, which they are using(like cloud foundry etc.) so Hystrix 2.4 is not compatible(got some compilation errors) with the old versions of stellteo packages. 

2.I got the below issue, when I started using Steeltoe.CircuitBreaker.Hystrix.MetricsStream (in start up i placed this command services.AddHystrixMetricsStream(Configuration); ), then i added RabbitMq client and the issue is resolved. I deployed in pcf and tested everything(hystrix dashboard, circuit open and close) working fine. suddenly its started giving an error in PCF after a week. I debugged and found the above error. 

Steeltoe.CloudFoundry.Connector.Connector.ConnectorException: 'Unable to find RabbitMQ connectionFactory type. RabbitMQ.Client assemby may be missing'

where I have to configure? do I need to configure something else?

**Comment by TimHess** [comment]
I'm suggesting you should update all the Steeltoe packages, there have been numerous improvements in that timeframe.

That `ConnectorException` happens when you don't have a compatible package reference to [RabbitMQ.Client](https://www.nuget.org/packages/RabbitMQ.Client) - Steeltoe Connectors use reflection to work with a variety drivers without direct references, so it is possible for there to be incompatibilities between versions that aren't known until runtime. There aren't any known incompatibilities there though - what version of RabbitMQ.Client are you using?  I can't imagine that part of this puzzle would break on its own post-deployment.

If the deployed application was working and then stopped after some time (with no code changes or redeployments) then it would be worth checking with the platform team to make sure there weren't any changes or problem with the network or any of the involved infrastructure.

**Comment by ravichigurupalli** [comment]
I am using RabbitMq.Client version 1.0.0. I contacted PCF foundations team. but i am facing this issue in local debugging as well.

**Comment by TimHess** [comment]
That version number doesn't sound right - is that the file version or the package version? That would be an _extremely_ old RabbitMQ client if that's the package version

Is your application running and throwing exceptions in the background or not running at all? I'm not clear on whether you're just having an issue seeing the metrics or if its interfering with the running of your application.

As far as I know, the Hystrix metrics stream (particularly over RabbitMQ) isn't very commonly used locally - how are you running the hystrix dashboard locally?

**Comment by ravichigurupalli** [comment]
I upgraded my application framework .net 2.1 to 3.1 and upgraded 
Steeltoe.CircuitBreaker.HystrixCore from 2.1.1 to 2.4.4
Steeltoe.CircuitBreaker.Hystrix.MetricsStreamCore 2.1.1 to 2.4.4
RabbitMQ.Client 1.0.0 to 6.1.0 and some other dependencies 
Still, I am facing the same issue.

When I got the error(means fallback user-defined error) in PCF, I debugged locally and I am able to repro the fallback user-defined error but i found the actual above RabbitMq error in the output window. Also, I am not running a dashboard locally. I am not sure what happens. I completely struck now.  

Steeltoe.CircuitBreaker.Hystrix.MetricsStream.RabbitMetricsStreamPublisher: Error: Error creating connection/channel, metrics streaming disabled: RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
 ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=530, text='NOT_ALLOWED - vhost / not found', classId=10, methodId=40
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.ConnectionOpen(String virtualHost, String capabilities, Boolean insist)
   at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at Steeltoe.CircuitBreaker.Hystrix.MetricsStream.RabbitMetricsStreamPublisher.EnsureConnection()
Steeltoe.CircuitBreaker.Hystrix.MetricsStream.RabbitMetricsStreamPublisher: Debug: Discarding Hystrix Metrics, no connection

**Comment by TimHess** [comment]
OK. There are several ways to resolve the metrics stream issue:
1. Run a RabbitMQ Server so the metrics have somewhere to go (probably not worth it if you're not hooking up a dashboard)
1. Turn off the failure logging (set `"Logging:LogLevel:Steeltoe.CircuitBreaker.Hystrix.MetricsStream"= "None"` in appsettings.development.json)
1. Conditionally activate the metrics stream based on the environment you're running in  (eg: `if (!env.IsDevelopment)`...)

But that all seems to have been a distraction this whole time, because the metrics stream happens in the background so it doesn't interfere with the application. It sounds like the fallback code you have is throwing it's own exception after the main method fails. I don't have any way to help you figure that out without knowing what either of those blocks of code are supposed to do, but your stack trace does also have `Exception thrown: 'System.NullReferenceException' in Dell.Product.TransformLayer.Services.dll` so maybe that's part of it?

**Comment by jkonicki** [comment]
Closing.  Respond to the comment from @TimHess, if you are still having this issue and we can reopen it.  

Thank you.

**Comment by ravichigurupalli** [comment]
Sure thank you
