### ISSUE TITLE
Create Sample to for using steel toe with K8s

### ISSUE THREAD

**Issue by VenkateshSrini** [SteeltoeOSS/Samples#174]
I do not find any samples for using STeelToe with K8s. Is there some code available for the same

**Comment by TimHess** [comment]
These two should run in k8s:

- [Configuration](https://github.com/SteeltoeOSS/Samples/tree/master/Configuration/src/Kubernetes)
- [Discovery](https://github.com/SteeltoeOSS/Samples/tree/master/Discovery/src)

Kubernetes samples will only be provided for master/3.0, but the default branch was 2.x  so that probably made them harder to find. We expect to be adding more and improving what's there over time, though there aren't specific plans beyond the [reference app](https://github.com/SteeltoeOSS/Steeltoe/issues/410)
