### ISSUE TITLE
I can't see mongodb credentials uri

### ISSUE THREAD

**Issue by jfernandezrico** [SteeltoeOSS/Samples#19]
When I access to Vcap Services in my dotnet core app using your Samples/Configuration/src/AspDotNetCore/CloudFoundry, I see mongodb key and I can navigate to credentials subkey, but uri is empty.

{
  "mongodb": [
   {
    "credentials": {
     "uri"
    },
    "label": "mongodb",
    "name": "app_name",
    "plan": "default",
    "tags": [
     "mongodb",
     "document"
    ]
   }
  ]
 }

If I run "cf env app_name" the uri has content.
Thank you

**Comment by dtillman** [comment]
@jfernandezrico,
Can you post the content (string) of the uri key... 
Dave

**Comment by dtillman** [comment]
@jfernandezrico:
Never mind I see what the problem is... my bad... I created this app from the SimpleCloudFoundry app, and forgot to include the taghelper that displays the service credentials...

I pushed in a commit on the dev branch that fixes the problem : https://github.com/SteeltoeOSS/Samples/commit/15b3754df36b65688fe9da51e3a217a030448560

Pull the dev branch and use that code, it should work!
Dave

**Comment by jfernandezrico** [comment]
Hi Dave,

Thank you very much for your contribution. I'll try it with the new code.

Kind regards,
